/*
 * Ultrasonic.c
 *
 * Description: Ultrasonic Driver using input capture unit
 *
 *  Created on: Oct 22, 2023
 *      Author: Mark
 */
#include "Ultrasonic.h"
#include "icu.h"
#include "gpio.h"
#include "util/delay.h"
#include <math.h>


/**************************************************************************************
 *                            Static FUNCTIONS PROTOTYPES                             *
 **************************************************************************************/

/*
 *Description : Send the Trigger pulse to the ultrasonic.
 */
static void Ultrasonic_Trigger(void);


/*
 * Description : This is the call back function called by the ICU driver.
 *  This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
static void Ultrasonic_edgeProcessing(void);






/**************************************************************************************
 *                               Global Variables                                     *
 **************************************************************************************/
static uint8 g_edges=0; /*to store the number of edges captured by the icu*/
static uint16 g_captureValue=0; /*to store the time between edges*/






/**************************************************************************************
 *                               Function Definition                                  *
 **************************************************************************************/

/*
 * initialize the ICU and ultrasonic trigger pin.
 */
void Ultrasonic_init(void){
	/*configure the icu to work with rising edge at first and the desired prescaler
	 * by creating a struct of type icu config type and initializing it with the
	 * required config*/
#if(ULTRASONIC_ICU_PRESCALER==8)
	ICU_ConfigType icu_config={F_CPU_8,RAISING};
#elif(ULTRASONIC_ICU_PRESCALER==1)
	ICU_ConfigType icu_config={F_CPU_CLOCK,RAISING};
#elif(ULTRASONIC_ICU_PRESCALER==64)
	ICU_ConfigType icu_config={F_CPU_64,RAISING};
#elif(ULTRASONIC_ICU_PRESCALER==256)
	ICU_ConfigType icu_config={F_CPU_256,RAISING};
#elif(ULTRASONIC_ICU_PRESCALER==1024)
	ICU_ConfigType icu_config={F_CPU_1024,RAISING};
#endif

	ICU_init(&icu_config); /*initializing the icu with the required config*/
	ICU_setCallBack(Ultrasonic_edgeProcessing); /*setting the call back function*/

	/*configure the trigger pin as output pin*/
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT,ULTRASONIC_TRIGGER_PIN,PIN_OUTPUT);

}




/*
 * to send a 10us pulse to the trigger pin.
 */

static void Ultrasonic_Trigger(void){
	/*writing logic high to the trigger pin*/
	GPIO_writePin(PORTB_ID,PIN5_ID,LOGIC_HIGH);
	_delay_us(10); /*maintaining the high logic for 10 us seconds*/
	GPIO_writePin(PORTB_ID,PIN5_ID,LOGIC_LOW); /*writing logic low to the pin to end the pulse*/
}




/*
 * this is the call back function to be called with each icu edge detection.
 */
static void Ultrasonic_edgeProcessing(void){
	g_edges++; /*increment edge every time the function is called*/

	/*on first call that's when the icu should start counting for the next falling edge
	 * so reset the timer to start counting and set the icu to detect falling edge*/
	if(g_edges==1){
		ICU_clearTimerValue();
		ICU_setEdgeDetectionType(FALLING);
	}

	/*the second call is when the falling edge is detected that's the high time of the echo
	 * pin that we need to calculate the distance.*/
	else if(g_edges==2){
		g_captureValue=ICU_getInputCaptureValue();/*store the time value captured by he icu*/
		ICU_clearTimerValue(); /*clear the timer to get ready for the next edge*/
		ICU_setEdgeDetectionType(RAISING);/*set icu to detect rising edge again*/
		g_edges=0; /*reset the number of edges to be ready for the comin rising edge*/
	}
}



/*
 * the function that sends the trigger and uses the captured time value to calculate
 * the distance.
 */
uint16 Ultrasonic_readDistance(){
	Ultrasonic_Trigger(); /*send trigger to start the ultrasonic*/
	_delay_ms(1); /*delay for the signal to be sent*/
	uint16 distance=0;
	/*calculate time taken by the timer tick according to the frequemcy of the cpu and the ICU prescaler*/
	uint32 tick_time=F_CPU/ULTRASONIC_ICU_PRESCALER;
	/*calculate the distance and round the result to the nearest integer*/
	 distance=round((double)(34000*(g_captureValue/2))/tick_time);
	return distance;
}
